//go:build ignore

// gen_cols.go reads testdata/TestOnlineDownloadReadme.txt and writes
// cols.gen.go containing Column definitions parsed from the GeoNames readme.
//
// Run via: go generate ./internal/pkg/geonames/cols/
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"strings"
)

// toGoName converts a readme column name like "feature class" to "FeatureClass".
func toGoName(col string) string {
	parts := strings.Fields(col)
	var sb strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		first := p[0]
		if first >= 'a' && first <= 'z' {
			first -= 32 // ASCII uppercase.
		}
		sb.WriteByte(first)
		sb.WriteString(strings.ToLower(p[1:]))
	}
	return sb.String()
}

// toDBCol converts a readme column name like "feature class" to "feature_class".
func toDBCol(col string) string {
	parts := strings.Fields(col)
	return strings.Join(parts, "_")
}

func main() {
	f, err := os.Open("testdata/TestOnlineDownloadReadme.txt")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	// Scan for the column definition section.
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
	inSection := false
	pastDashes := false

	type col struct {
		name string
		desc string
	}
	var cols []col

	for scanner.Scan() {
		line := scanner.Text()

		if strings.Contains(line, "The main 'geoname' table has the following fields") {
			inSection = true
			continue
		}
		if inSection && !pastDashes {
			if strings.HasPrefix(line, "---") {
				pastDashes = true
			}
			continue
		}
		if inSection && pastDashes {
			trimmed := strings.TrimSpace(line)
			if trimmed == "" {
				break // End of column definitions.
			}
			parts := strings.SplitN(line, ":", 2)
			if len(parts) != 2 {
				continue
			}
			name := strings.TrimSpace(parts[0])
			desc := strings.TrimSpace(parts[1])
			cols = append(cols, col{name: name, desc: desc})
		}
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "scanning readme:", err)
		os.Exit(1)
	}

	if len(cols) == 0 {
		fmt.Fprintln(os.Stderr, "no columns found in readme")
		os.Exit(1)
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by gen_cols.go; DO NOT EDIT.\n\npackage cols\n\n")

	// Individual column constants.
	sb.WriteString("// Column index constants for the GeoNames tab-delimited format.\nconst (\n")
	for i, c := range cols {
		fmt.Fprintf(&sb, "\tIdx%s = %d\n", toGoName(c.name), i)
	}
	sb.WriteString(")\n\n")

	// NumColumns constant.
	fmt.Fprintf(&sb, "// NumColumns is the expected number of tab-delimited columns.\nconst NumColumns = %d\n\n", len(cols))

	// DB column name constants.
	sb.WriteString("// DB column name constants.\nconst (\n")
	for _, c := range cols {
		fmt.Fprintf(&sb, "\tDB%s = %q\n", toGoName(c.name), toDBCol(c.name))
	}
	sb.WriteString(")\n\n")

	// Columns slice.
	sb.WriteString("// Columns lists all columns in the GeoNames main table in order.\n")
	sb.WriteString("var Columns = []Column{\n")
	for i, c := range cols {
		fmt.Fprintf(&sb, "\t{Index: %d, Name: %q, GoName: %q, Description: %q},\n",
			i, c.name, toGoName(c.name), c.desc)
	}
	sb.WriteString("}\n")

	out, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "formatting generated source:", err)
		fmt.Fprint(os.Stderr, sb.String())
		os.Exit(1)
	}

	if err := os.WriteFile("cols.gen.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
