//go:build ignore

// gen_feature_codes.go reads testdata/TestOnlineDownloadFeatureCodes.txt and
// writes feature_codes.gen.go containing feature code constants and metadata.
//
// Run via: go generate ./internal/pkg/geonames/cols/
package main

import (
	"bufio"
	"fmt"
	"go/format"
	"os"
	"strings"
)

type featureCode struct {
	class string // e.g. "A"
	code  string // e.g. "ADM1"
	name  string // e.g. "first-order administrative division"
	desc  string // e.g. "a primary administrative division of a country, ..."
}

// toConstName converts a feature code like "ADM1" to a Go-friendly constant
// suffix. Digits and uppercase letters are kept as-is.
func toConstName(code string) string {
	return strings.ReplaceAll(code, ".", "_")
}

func main() {
	f, err := os.Open("testdata/TestOnlineDownloadFeatureCodes.txt")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	var codes []featureCode
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "null") {
			continue
		}

		parts := strings.SplitN(line, "\t", 3)
		if len(parts) < 2 {
			continue
		}

		classCode := strings.SplitN(parts[0], ".", 2)
		if len(classCode) != 2 {
			continue
		}

		desc := ""
		if len(parts) == 3 {
			desc = parts[2]
		}

		codes = append(codes, featureCode{
			class: classCode[0],
			code:  classCode[1],
			name:  parts[1],
			desc:  desc,
		})
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "scanning feature codes:", err)
		os.Exit(1)
	}
	if len(codes) == 0 {
		fmt.Fprintln(os.Stderr, "no feature codes found")
		os.Exit(1)
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by gen_feature_codes.go; DO NOT EDIT.\n\npackage cols\n\n")

	// Feature class constants.
	classes := []struct {
		letter string
		name   string
	}{
		{"A", "Administrative"},
		{"H", "Hydrographic"},
		{"L", "Area"},
		{"P", "PopulatedPlace"},
		{"R", "Road"},
		{"S", "Spot"},
		{"T", "Hypsographic"},
		{"U", "Undersea"},
		{"V", "Vegetation"},
	}
	sb.WriteString("// Feature class constants.\nconst (\n")
	for _, c := range classes {
		fmt.Fprintf(&sb, "\tFeatureClass%s = %q\n", c.name, c.letter)
	}
	sb.WriteString(")\n\n")

	// Feature code constants, grouped by class.
	currentClass := ""
	for _, fc := range codes {
		if fc.class != currentClass {
			if currentClass != "" {
				sb.WriteString(")\n\n")
			}
			className := fc.class
			for _, c := range classes {
				if c.letter == fc.class {
					className = c.name
					break
				}
			}
			fmt.Fprintf(&sb, "// Feature codes for class %s (%s).\nconst (\n", fc.class, className)
			currentClass = fc.class
		}
		fmt.Fprintf(&sb, "\tFeatureCode%s = %q\n", toConstName(fc.code), fc.code)
	}
	if currentClass != "" {
		sb.WriteString(")\n\n")
	}

	// FeatureCode struct and slice.
	sb.WriteString("// FeatureCode describes a single GeoNames feature code.\n")
	sb.WriteString("type FeatureCode struct {\n")
	sb.WriteString("\t// Class is the single-letter feature class (e.g. \"P\").\n")
	sb.WriteString("\tClass string\n")
	sb.WriteString("\t// Code is the feature code within the class (e.g. \"PPLA\").\n")
	sb.WriteString("\tCode string\n")
	sb.WriteString("\t// Name is the short human-readable name (e.g. \"seat of a first-order administrative division\").\n")
	sb.WriteString("\tName string\n")
	sb.WriteString("\t// Description is the longer explanation.\n")
	sb.WriteString("\tDescription string\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// FeatureCodes lists all GeoNames feature codes.\n")
	sb.WriteString("var FeatureCodes = []FeatureCode{\n")
	for _, fc := range codes {
		fmt.Fprintf(&sb, "\t{Class: %q, Code: %q, Name: %q, Description: %q},\n",
			fc.class, fc.code, fc.name, fc.desc)
	}
	sb.WriteString("}\n")

	out, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "formatting generated source:", err)
		fmt.Fprint(os.Stderr, sb.String())
		os.Exit(1)
	}

	if err := os.WriteFile("feature_codes.gen.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
