package main

import (
	"bytes"
	"flag"
	"os"
	"testing"

	"github.com/alexflint/go-arg"
	"github.com/stretchr/testify/require"
)

var updateConfigDoc = flag.Bool("update-options-doc", false, "update OPTIONS.md from config struct")

// TestConfigDoc verifies that OPTIONS.md is up to date with the config struct.
// Run with -update-config-doc to regenerate the file.
func TestOptionsDoc(t *testing.T) {
	var buf bytes.Buffer
	buf.WriteString("<!--\nAutogenerated, do not edit. \nRegenerate: go test -run TestOptionsDoc -update-options-doc\n-->\n")
	buf.WriteString("# Configuration\n\n")
	buf.WriteString("All options can be passed as CLI flags or environment variables.\n\n")

	buf.WriteString("```\n")
	c := config{}
	p, err := arg.NewParser(arg.Config{Program: "detour"}, &c)
	require.NoError(t, err)
	err = p.WriteHelpForSubcommand(&buf, "serve")
	require.NoError(t, err)
	buf.WriteString("```\n")

	want := buf.String()

	if *updateConfigDoc {
		err := os.WriteFile("OPTIONS.md", []byte(want), 0o644)
		require.NoError(t, err)
		t.Log("OPTIONS.md updated")
		return
	}

	got, err := os.ReadFile("OPTIONS.md")
	if os.IsNotExist(err) {
		t.Fatal("OPTIONS.md does not exist; run with -update-config-doc to generate it")
	}
	require.NoError(t, err)
	require.Equal(t, want, string(got), "OPTIONS.md is out of date; run: go test -run TestConfigDoc -update-config-doc")
}
