openapi: 3.0.3
info:
  title: User API
  version: 1.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: Main page
          content:
            text/html:
              schema:
                type: string
  /sessions/login:
    get:
      tags: [sessions]
      responses:
        '200':
          description: Login form
          content:
            text/html:
              schema:
                type: string
    post:
      tags: [sessions]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '302':
          description: Login successful
          headers:
            Location:
              schema:
                type: string
                format: uri
        '401':
          description: Login failed
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            text/html:
              schema:
                type: string
  /sessions/logout:
    get:
      tags: [sessions]
      security:
        - CookieAuth: []
      responses:
        '200':
          description: Logout form
          content:
            text/html:
              schema:
                type: string
    post:
      tags: [sessions]
      security:
        - CookieAuth: []
      responses:
        '302':
          description: Logout successful
          headers:
            Location:
              schema:
                type: string
                format: uri
        '500':
          description: Internal server error
          content:
            text/html:
              schema:
                type: string
  /api/v1/users:
    get:
      tags: [users]
      security:
        - CookieAuth: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          $ref: '#/components/responses/500InternalServerError'
    post:
      tags: [users]
      security:
        - CookieAuth: []
      parameters:
        - $ref: "#/components/parameters/AcceptHeader"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '409':
          $ref: '#/components/responses/409Conflict'
        '500':
          $ref: '#/components/responses/500InternalServerError'
  /api/v1/users/{id}:
    get:
      tags: [users]
      security:
        - CookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalServerError'
    put:
      tags: [users]
      security:
        - CookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '409':
          $ref: '#/components/responses/409Conflict'
        '500':
          $ref: '#/components/responses/500InternalServerError'
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: session_id
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
      required:
        - email
        - name
    Login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    ErrorJSON:
      type: object
      properties:
        message:
          type: string
        errors:
          type: object
          nullable: true
          additionalProperties:
            $ref: '#/components/schemas/ErrorJSON'
      required:
        - message
        - errors

  parameters:
    AcceptHeader:
      in: header
      name: Accept
      required: true
      schema:
        type: string
  responses:
    200OK:
      description: OK
    200Form:
      description: HTML Form
      content:
        text/html:
          schema:
            type: string
    201Created:
      description: Created
    204NoContent:
      description: No content
    400BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJSON'
        text/html:
          schema:
            type: string
    401Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJSON'
        text/html:
          schema:
            type: string
    404NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJSON'
        text/html:
          schema:
            type: string
    409Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJSON'
        text/html:
          schema:
            type: string
    500InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorJSON'
        text/html:
          schema:
            type: string
