//go:build ignore

// gen_vars.go reads testdata/TestOnlineFetchVariablesCSV.csv and writes
// vars.gen.go containing named Variable vars and the Variables slice.
//
// Run via: go generate ./internal/pkg/meteo/vars/
package main

import (
	"encoding/csv"
	"fmt"
	"go/format"
	"io"
	"os"
	"strings"
)

// toVarName converts a parameter code like "ALB_RAD" to a Go identifier like
// "VarAlbRad". Each underscore-separated segment is title-cased; segments
// starting with a digit are lowercased after the digit.
func toVarName(param string) string {
	parts := strings.Split(param, "_")
	var sb strings.Builder
	sb.WriteString("Var")
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		first := part[0]
		if first >= 'a' && first <= 'z' {
			first -= 32 // ASCII uppercase.
		}
		sb.WriteByte(first)
		sb.WriteString(strings.ToLower(part[1:]))
	}
	return sb.String()
}

func main() {
	f, err := os.Open("testdata/TestOnlineFetchVariablesCSV.csv")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	r := csv.NewReader(f)
	// Skip the header row.
	if _, err := r.Read(); err != nil {
		fmt.Fprintln(os.Stderr, "reading CSV header:", err)
		os.Exit(1)
	}

	type record struct {
		varName string
		fields  [8]string
	}
	var records []record

	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Fprintln(os.Stderr, "reading CSV record:", err)
			os.Exit(1)
		}
		if len(rec) < 8 {
			continue
		}
		var fields [8]string
		copy(fields[:], rec[:8])
		records = append(records, record{varName: toVarName(rec[0]), fields: fields})
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by gen_vars.go; DO NOT EDIT.\n\npackage vars\n\n")

	for _, rec := range records {
		f := rec.fields
		fmt.Fprintf(&sb, "// %s is the forecast variable for %q.\n", rec.varName, f[0])
		fmt.Fprintf(&sb, "var %s = Variable{\n", rec.varName)
		fmt.Fprintf(&sb, "\tName:                %q,\n", f[0])
		fmt.Fprintf(&sb, "\tLongName:            %q,\n", f[1])
		fmt.Fprintf(&sb, "\tUnit:                %q,\n", f[2])
		fmt.Fprintf(&sb, "\tLevel:               %q,\n", f[3])
		fmt.Fprintf(&sb, "\tVerticalCoordinate:  %q,\n", f[4])
		fmt.Fprintf(&sb, "\tHorizon:             %q,\n", f[5])
		fmt.Fprintf(&sb, "\tTemporalAggregation: %q,\n", f[6])
		fmt.Fprintf(&sb, "\tAggregationStart:    %q,\n", f[7])
		fmt.Fprintf(&sb, "}\n\n")
	}

	// Build Variables slice referencing the named vars.
	sb.WriteString("// Variables is the list of all available ICON-CH1-EPS forecast variables,\n")
	sb.WriteString("// generated from testdata/TestOnlineFetchVariablesCSV.csv.\n")
	sb.WriteString("var Variables = []Variable{\n")
	for _, rec := range records {
		fmt.Fprintf(&sb, "\t%s,\n", rec.varName)
	}
	sb.WriteString("}\n")

	out, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "formatting generated source:", err)
		fmt.Fprint(os.Stderr, sb.String())
		os.Exit(1)
	}

	if err := os.WriteFile("vars.gen.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
