//go:build ignore

// gen_params.go reads testdata/TestOnlineFetchParamsCSV.csv and writes
// params.gen.go containing named Param vars and the Params slice.
//
// Run via: go generate ./internal/pkg/grib2/params/
package main

import (
	"encoding/csv"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// entry holds a parsed WMO GRIB2 Table 4.2 row.
type entry struct {
	Name       string
	GoName     string
	Discipline uint8
	Category   uint8
	Number     uint8
}

// toParamName converts a WMO label like "U-component of wind" to a Go
// identifier like "ParamUComponentOfWind". Each run of non-alphanumeric ASCII
// characters acts as a word separator; each word is title-cased. Non-ASCII
// runes are dropped so the result is always a pure ASCII identifier.
func toParamName(label string) string {
	words := strings.FieldsFunc(label, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var sb strings.Builder
	sb.WriteString("Param")
	for _, w := range words {
		// Map non-ASCII runes to ASCII equivalents; unknown ones are dropped.
		var ascii strings.Builder
		for _, r := range w {
			switch {
			case r < 128:
				ascii.WriteRune(r)
			case r == 'μ' || r == 'µ': // U+03BC / U+00B5
				ascii.WriteRune('u')
			}
		}
		s := ascii.String()
		if len(s) == 0 {
			continue
		}
		sb.WriteString(strings.ToUpper(s[:1]) + strings.ToLower(s[1:]))
	}
	return sb.String()
}

// parsePrefLabel extracts the English text from a skos:prefLabel value like
// `'Temperature'@en`.
func parsePrefLabel(raw string) string {
	raw = strings.TrimSpace(raw)
	if after, ok := strings.CutPrefix(raw, "'"); ok {
		raw = after
		if i := strings.LastIndex(raw, "'"); i >= 0 {
			raw = raw[:i]
		}
	}
	return strings.TrimSpace(raw)
}

func main() {
	f, err := os.Open("testdata/TestOnlineFetchParamsCSV.csv")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.LazyQuotes = true
	rows, err := r.ReadAll()
	if err != nil {
		fmt.Fprintln(os.Stderr, "reading CSV:", err)
		os.Exit(1)
	}
	if len(rows) < 2 {
		fmt.Fprintln(os.Stderr, "CSV too short")
		os.Exit(1)
	}

	// Locate @id and skos:prefLabel columns by header name.
	idCol, labelCol := -1, -1
	for i, h := range rows[0] {
		switch strings.Trim(h, "<>") {
		case "@id":
			idCol = i
		case "skos:prefLabel":
			labelCol = i
		}
	}
	if idCol < 0 || labelCol < 0 {
		fmt.Fprintln(os.Stderr, "required columns not found in header")
		os.Exit(1)
	}

	// Parse rows into entries.
	var entries []entry
	for _, row := range rows[1:] {
		if len(row) <= idCol || len(row) <= labelCol {
			continue
		}

		// Extract D-C-N from the trailing path segment of the @id URI.
		id := strings.Trim(row[idCol], "<>")
		slash := strings.LastIndex(id, "/")
		if slash < 0 {
			continue
		}
		parts := strings.SplitN(id[slash+1:], "-", 3)
		if len(parts) != 3 {
			continue
		}
		d, err1 := strconv.ParseUint(parts[0], 10, 8)
		c, err2 := strconv.ParseUint(parts[1], 10, 8)
		n, err3 := strconv.ParseUint(parts[2], 10, 8)
		if err1 != nil || err2 != nil || err3 != nil {
			continue
		}

		label := parsePrefLabel(row[labelCol])
		if label == "" || label == "Missing" {
			continue
		}
		entries = append(entries, entry{
			Name:       label,
			Discipline: uint8(d),
			Category:   uint8(c),
			Number:     uint8(n),
		})
	}

	// Assign Go names, disambiguating duplicates with a _D_C_N suffix.
	used := make(map[string]int, len(entries))
	for i := range entries {
		name := toParamName(entries[i].Name)
		if used[name] > 0 {
			name = fmt.Sprintf("%s_%d_%d_%d", name,
				entries[i].Discipline, entries[i].Category, entries[i].Number)
		}
		used[name]++
		entries[i].GoName = name
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by gen_params.go; DO NOT EDIT.\n\npackage params\n\n")

	for _, e := range entries {
		fmt.Fprintf(&sb, "// %s is the WMO GRIB2 parameter for %q (%d-%d-%d).\n",
			e.GoName, e.Name, e.Discipline, e.Category, e.Number)
		fmt.Fprintf(&sb, "var %s = Param{%d, %d, %d}\n\n",
			e.GoName, e.Discipline, e.Category, e.Number)
	}

	// Params slice referencing the named vars.
	sb.WriteString("// Params is the list of all WMO GRIB2 Table 4.2 parameters,\n")
	sb.WriteString("// generated from testdata/TestOnlineFetchParamsCSV.csv.\n")
	sb.WriteString("var Params = []Param{\n")
	for _, e := range entries {
		fmt.Fprintf(&sb, "\t%s,\n", e.GoName)
	}
	sb.WriteString("}\n")

	out, err := format.Source([]byte(sb.String()))
	if err != nil {
		fmt.Fprintln(os.Stderr, "formatting generated source:", err)
		fmt.Fprint(os.Stderr, sb.String())
		os.Exit(1)
	}

	if err := os.WriteFile("params.gen.go", out, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
