package load

import (
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"jo-m.ch/go/detour/internal/pkg/track"
)

func ptr(s string) *string { return &s }

func timePtr() *time.Time {
	t := time.Date(2024, 1, 1, 12, 0, 0, 0, time.UTC)
	return &t
}

func TestDetectTrackType(t *testing.T) {
	tests := []struct {
		name     string
		gpx      GPX
		expected track.TrackType
	}{
		{
			name: "garmin recorded: ACTIVITY in filename",
			gpx: GPX{
			filename: "ACTIVITY_123456.gpx",
				XMetadata: Metadata{
					Name: ptr("My Route"),
					Link: &Link{Href: "connect.garmin.com"},
				},
				Tracks: []Track{{Name: "My Route"}},
			},
			expected: track.TrackTypeRecorded,
		},
		{
			name: "garmin planned: COURSE in filename",
			gpx: GPX{
				filename: "COURSE_436298480.gpx",
				XMetadata: Metadata{
					Link: &Link{Href: "connect.garmin.com"},
				},
				Tracks: []Track{{Name: "Zurich Road Cycling"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "garmin recorded: name in trk only, no filename hint",
			gpx: GPX{
				filename: "export.gpx",
				XMetadata: Metadata{
					Link: &Link{Href: "connect.garmin.com"},
				},
				Tracks: []Track{{Name: "Zurich Road Cycling"}},
			},
			expected: track.TrackTypeRecorded,
		},
		{
			name: "garmin planned: name in both metadata and trk, no filename hint",
			gpx: GPX{
				filename: "export.gpx",
				XMetadata: Metadata{
					Name: ptr("My Route"),
					Link: &Link{Href: "connect.garmin.com"},
				},
				Tracks: []Track{{Name: "My Route"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "garmin planned: name in metadata only",
			gpx: GPX{
				XMetadata: Metadata{
					Name: ptr("My Route"),
					Link: &Link{Href: "connect.garmin.com"},
				},
				Tracks: []Track{{}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "strava recorded: no author info",
			gpx: GPX{
				XMetadata: Metadata{},
				Tracks:    []Track{{Name: "Morning Ride"}},
			},
			expected: track.TrackTypeRecorded,
		},
		{
			name: "strava planned: has author name and link",
			gpx: GPX{
				XMetadata: Metadata{
					Author: &Author{
						Name: "John Doe",
						Link: &Link{Href: "https://www.strava.com/athletes/12345"},
					},
				},
				Tracks: []Track{{Name: "My Planned Route"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "strava planned: has author name only",
			gpx: GPX{
				XMetadata: Metadata{
					Author: &Author{Name: "John Doe"},
				},
				Tracks: []Track{{Name: "My Route"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "strava planned: has author link only",
			gpx: GPX{
				XMetadata: Metadata{
					Author: &Author{
						Link: &Link{Href: "https://www.strava.com/athletes/12345"},
					},
				},
				Tracks: []Track{{Name: "My Route"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "other source with author: planned",
			gpx: GPX{
				XMetadata: Metadata{
					Author: &Author{
						Link: &Link{Href: "https://www.komoot.de"},
					},
				},
				Tracks: []Track{{Name: "My Route"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "schweizmobil: always planned",
			gpx: GPX{
				Creator:   "MySchweizMobil - https://map.schweizmobil.ch/",
				XMetadata: Metadata{},
				Tracks:    []Track{{Name: "Bern to Thun"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "cycle.travel: always planned",
			gpx: GPX{
				Creator:   "cycle.travel",
				XMetadata: Metadata{},
				Tracks:    []Track{{Name: "Route"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "swisstopo: always planned",
			gpx: GPX{
				Creator:   "Generated by Swisstopo App. See https://www.swisstopo.ch/app for more information.",
				XMetadata: Metadata{},
				Tracks:    []Track{{Name: "My Tour"}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "planning-only creator takes precedence even with timestamps",
			gpx: GPX{
				Creator:   "https://map.schweizmobil.ch/",
				XMetadata: Metadata{},
				Tracks: []Track{{Segments: []TrackSegment{{
					Points: []TrackPoint{{Time: timePtr()}},
				}}}},
			},
			expected: track.TrackTypePlanned,
		},
		{
			name: "no timestamps and no author: planned",
			gpx: GPX{
				Creator:   "SomeUnknownTool",
				XMetadata: Metadata{Author: &Author{Name: "user"}},
				Tracks: []Track{{Segments: []TrackSegment{{
					Points: []TrackPoint{{Lat: 47.0, Lon: 8.0}},
				}}}},
			},
			expected: track.TrackTypePlanned,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := tt.gpx.detectTrackType()
			require.Equal(t, tt.expected, got)
		})
	}
}
